### ISSUE TITLE
Column Summaries dialog query

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat-Translations#2]
From @rdstern here https://github.com/africanmathsinitiative/R-Instat/issues/5096#issuecomment-459267875
@rdstern can you confirm, are you suggesting a change to the English as well as the French?
> 1.) In the dialogue of Column: Reshape > Column Summaries on rhs it just says Des. That is going to be Proportion/Pourcentiles. Let's shorten to Propn and omit Des.

**Comment by rdstern** [comment]
I don't mind.  I was thinking of the French here, but it could be Propn/Percentile or even Propn/%ile.  But writing both these I prefer we keep the English as it is.
In the French I have now seen your solution for Data Options of changing the font size.  So I wonder if that could be used here.  Still get rid of Des at the front.

**Comment by dannyparsons** [comment]
How about:
English: `Prop. and percentages...`
French: `Prop. et pourcentages...`

These both fit with the current font size.

**Comment by rdstern** [comment]
OK, fine

**Comment by dannyparsons** [comment]
@Ivanluv @Wycklife @Muthenya could someone make the change to the button text in English? 
I'll update the French version.

**Comment by Muthenya** [comment]
Okay.
