### ISSUE TITLE
Temporary switching between languages 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat-Translations#3]
1. **Language:** French
2. **Dialog (or location)**:
3. **Current Text in English**:
4. **Current Text in other language**:
5. **Suggested text in other language**:
6. **Reason for the suggested change**:

6. The option to switch languages within a dialogue is very nice.  How could we switch languages like that in the menus?

I suppose one way would be a Language option on the Right click menu?  It is disabled if working in English.   Perhaps there is a better way, e.g. on the toolbar?

**Comment by dannyparsons** [comment]
I'll move this issue to R-Instat repo as its a software issue not a language issue.
