### ISSUE TITLE
 Prepare > Column:Factors > Combine Factors separator translation query

### ISSUE THREAD

**Issue by Muthenya** [africanmathsinitiative/R-Instat-Translations#4]
1. **Language:** 
French

2. **Dialog (or location)**:
Prepare > Column:Factors > Combine Factors

3. **Current Text in English**:
`separator`
4. **Current Text in other language**:
`caractère de\ nséparation`

5. **Suggested text in other language**:
 `séparateur`

6. **Reason for the suggested change**:
It's a much shorter and more precise translation of separator.

**Comment by dannyparsons** [comment]
Thanks, I've added this for the next release.
