### ISSUE TITLE
Describe > Specific > Boxplot

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat-Translations#7]
1. **Language:** French
2. **Dialog (or location)**:
Boxplot

3. **Current Text in English**:

Buttons at the top are Jitter Plot and Violin Plot

4. **Current Text in other language**:
Parcelle de, etc

5. **Suggested text in other language**:
Change Parcelle to Graphique

6. **Reason for the suggested change**:
Parcelle is plot as in a plot of land not a graph.

**Comment by dannyparsons** [comment]
Thanks, I have found more cases of this in the file: "Rug Plot", "Parallel Coordinate Plot" etc. 
I assume they would all be improved by a change from Parcelle to Graphique?

**Comment by rdstern** [comment]
Absolutely.  I was starting to look for that, but got sidetracked on histograms.

**Comment by dannyparsons** [comment]
Great, I've made those changes.
