### ISSUE TITLE
Describe > Specific > Lineplot

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat-Translations#8]
1. **Language:** French
2. **Dialog (or location)**:

Line plot
3. **Current Text in English**:
a) At the very top it says (something like) Line Plot
b) Line-plot options button
c) Plot options button

4. **Current Text in other language**:

Terrain de ligne

5. **Suggested text in other language**:
a) Instead have Graphique Linéaire
b) I suggest Options des lignes
c) I suggest Options de graphique (not trace - and this is on all the plot dialogues.)

6. **Reason for the suggested change**:

**Comment by dannyparsons** [comment]
Thanks, done and found in other places to change too.
